[package]
name = "geospatial_service"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
geo = "0.24" # for geospatial calculations
geo-types = "0.6" # to define geometric types
log = "0.4"
env_logger = "0.10"