name: CI/CD NRA

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      rabbitmq:
        image: rabbitmq:3-management
        ports:
          - 5672:5672
          - 15672:15672

    strategy:
      matrix:
        app: [driver, notification, nuber-app, trip, user-service]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Install dependencies for ${matrix.app}
      working-directory: apps/${{ matrix.app }}
      run: npm install

    - name: Build ${matrix.app}
      working-directory: apps/${{ matrix.app }}
      run: npm run build

    - name: Run tests for ${matrix.app}
      working-directory: apps/${{ matrix.app }}
      run: npm run test

  lint:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        app: [driver, notification, nuber-app, trip, user-service]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Install dependencies for ${matrix.app}
      working-directory: apps/${{ matrix.app }}
      run: npm install

    - name: Lint ${matrix.app}
      working-directory: apps/${{ matrix.app }}
      run: npm run lint
