name: CI/CD NRA APP

on:
  push:
    branches:
      - master
      - develop  
  pull_request:
    branches:
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      rabbitmq:
        image: rabbitmq:3-management
        ports:
          - 5672:5672
          - 15672:15672

    strategy:
      matrix:
        app: [driver, notification, gateway, ride, user-service, auth, user]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Install dependencies for ${{ matrix.app }}
      working-directory: apps/${{ matrix.app }}
      run: npm install

    #- name: Build ${{ matrix.app }}
    #  working-directory: apps/${{ matrix.app }}
    #  run: npm run build

    - name: Start ${{ matrix.app }}
      working-directory: apps/${{ matrix.app }}
      run: nest start ${{ matrix.app }} &

    - name: Run tests for ${{ matrix.app }}
      working-directory: apps/${{ matrix.app }}
      run: npm run test
